services:
  postgres:
    image: postgres:16
    container_name: wagerplay_postgres
    environment:
      POSTGRES_USER: wagerplay
      POSTGRES_PASSWORD: wagerplay
      POSTGRES_DB: wagerplay
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: wagerplay_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
